
-- 请在 Supabase Dashboard 的 SQL Editor 中运行此脚本

-- 1. 创建用户额度表
create table public.user_credits (
  user_id uuid references auth.users not null primary key,
  credits_remaining int default 5
);

-- 2. 启用行级安全 (RLS)
alter table public.user_credits enable row level security;

-- 3. 策略：用户只能查看自己的额度
create policy "Users can view their own credits"
  on public.user_credits for select
  using (auth.uid() = user_id);

-- 4. 策略：允许用户更新自己的额度 (用于扣除额度)
create policy "Users can update their own credits"
  on public.user_credits for update
  using (auth.uid() = user_id);

-- 5. 触发器：新用户注册时自动赠送 5 次额度
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.user_credits (user_id, credits_remaining)
  values (new.id, 5);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. 创建发票历史记录表
create table public.invoice_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  vendor_name text,
  total_amount text,
  currency text,
  invoice_number text
);

-- 7. 启用历史记录表的 RLS
alter table public.invoice_history enable row level security;

-- 8. 策略：用户只能查看和插入自己的历史记录
create policy "Users can view their own history"
  on public.invoice_history for select
  using (auth.uid() = user_id);

create policy "Users can insert their own history"
  on public.invoice_history for insert
  with check (auth.uid() = user_id);
